### ISSUE TITLE
undefined method `nested_fields_for' for #<ActionView::Helpers::FormBuilder

### ISSUE THREAD

**Issue by osnysantos** [ncri/nested_form_fields#76]
On localhost is working like a charm, but on production I'm getting this error:

```
NoMethodError: undefined method `nested_fields_for' for #<ActionView::Helpers::FormBuilder:0x00000002a197b0>
```

I've checked and nested_form_field is correctly set on Gemfile, with rails 4 and ruby 2.1.
Here is the full trace:

```
[PROJECT_ROOT]/app/views/webinar_questions/_form.html.erb:35:in `block in _app_views_webinar_questions__form_html_erb__45301749637291857_47344440'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/helpers/capture_helper.rb:38:in `capture'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/helpers/form_helper.rb:435:in `form_for'
[PROJECT_ROOT]/app/views/webinar_questions/_form.html.erb:1:in `_app_views_webinar_questions__form_html_erb__45301749637291857_47344440'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/template.rb:143:in `block in render'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `block in instrument'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `instrument'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/template.rb:141:in `render'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `block in instrument'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `instrument'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/renderer/partial_renderer.rb:278:in `render'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/renderer/renderer.rb:47:in `render_partial'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/helpers/rendering_helper.rb:27:in `render'
[PROJECT_ROOT]/app/views/webinar_questions/new.html.erb:3:in `_app_views_webinar_questions_new_html_erb___1863366937932933150_47380300'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/template.rb:143:in `block in render'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `block in instrument'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `instrument'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/template.rb:141:in `render'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/renderer/template_renderer.rb:49:in `block (2 levels) in render_template'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `block in instrument'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `instrument'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/renderer/template_renderer.rb:48:in `block in render_template'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/renderer/template_renderer.rb:56:in `render_with_layout'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/renderer/template_renderer.rb:47:in `render_template'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/renderer/template_renderer.rb:17:in `render'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/renderer/renderer.rb:42:in `render_template'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_view/renderer/renderer.rb:23:in `render'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/abstract_controller/rendering.rb:127:in `_render_template'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/streaming.rb:219:in `_render_template'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/abstract_controller/rendering.rb:120:in `render_to_body'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/rendering.rb:33:in `render_to_body'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/renderers.rb:26:in `render_to_body'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/abstract_controller/rendering.rb:97:in `render'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/rendering.rb:16:in `render'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/deployer/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/core_ext/benchmark.rb:12:in `ms'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
[GEM_ROOT]/gems/activerecord-4.0.0/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:40:in `render'
[GEM_ROOT]/gems/wicked_pdf-0.11.0/lib/wicked_pdf/pdf_helper.rb:23:in `render_with_wicked_pdf'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/responder.rb:233:in `default_render'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/responder.rb:161:in `to_html'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/responder.rb:154:in `respond'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/responder.rb:147:in `call'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/mime_responds.rb:330:in `respond_with'
[PROJECT_ROOT]/app/controllers/webinar_questions_controller.rb:24:in `new'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/abstract_controller/base.rb:189:in `process_action'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/rendering.rb:10:in `process_action'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:433:in `_run__3111297450711535740__process_action__callbacks'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb:17:in `process_action'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `block in instrument'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `instrument'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
[GEM_ROOT]/gems/activerecord-4.0.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/abstract_controller/base.rb:136:in `process'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/abstract_controller/rendering.rb:44:in `process'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal.rb:195:in `dispatch'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_controller/metal.rb:231:in `block in action'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:80:in `call'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:48:in `call'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:71:in `block in call'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:59:in `each'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:59:in `call'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:655:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
[GEM_ROOT]/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
[GEM_ROOT]/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/warden-1.2.4/lib/warden/manager.rb:35:in `block in call'
[GEM_ROOT]/gems/warden-1.2.4/lib/warden/manager.rb:34:in `catch'
[GEM_ROOT]/gems/warden-1.2.4/lib/warden/manager.rb:34:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/rack-1.5.5/lib/rack/conditionalget.rb:25:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/middleware/flash.rb:241:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
[GEM_ROOT]/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/middleware/cookies.rb:486:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/activerecord-4.0.0/lib/active_record/query_cache.rb:36:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:373:in `_run__545859884188748164__call__callbacks'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/railties-4.0.0/lib/rails/rack/logger.rb:38:in `call_app'
[GEM_ROOT]/gems/railties-4.0.0/lib/rails/rack/logger.rb:21:in `block in call'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:67:in `block in tagged'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:25:in `tagged'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:67:in `tagged'
[GEM_ROOT]/gems/railties-4.0.0/lib/rails/rack/logger.rb:21:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/activesupport-4.0.0/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/actionpack-4.0.0/lib/action_dispatch/middleware/static.rb:64:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/railties-4.0.0/lib/rails/engine.rb:511:in `call'
[GEM_ROOT]/gems/railties-4.0.0/lib/rails/application.rb:97:in `call'
[GEM_ROOT]/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[GEM_ROOT]/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:562:in `process_client'
[GEM_ROOT]/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:658:in `worker_loop'
[GEM_ROOT]/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
[GEM_ROOT]/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:519:in `maintain_worker_count'
[GEM_ROOT]/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:283:in `join'
[GEM_ROOT]/gems/unicorn-5.0.1/bin/unicorn:126:in `<top (required)>'
[GEM_ROOT]/bin/unicorn:23:in `load'
[GEM_ROOT]/bin/unicorn:23:in `<main>'
```

**Comment by ncri** [comment]
Sounds like a gem version issue. Odd. I assume you use bundler locally and on the server?

**Comment by osnysantos** [comment]
@ncri sure, I'm using bundler (1.11.2), nested_form_fields version 0.7.8

**Comment by ncri** [comment]
Can you post the code for your form?

**Comment by osnysantos** [comment]
Gemfile
```
source 'https://rubygems.org'
gem 'rails', '4.0.0'
...
gem 'nested_form_fields'
...
```

app/models/webinar_question.rb
```
class WebinarQuestion < ActiveRecord::Base
  belongs_to :webinar
  has_many :webinar_answers
  accepts_nested_attributes_for :webinar_answers, :allow_destroy => true
```

app/views/webinar_questions/_form.html.erb
```
<%= form_for(@webinar_question, :html => {:class => "form-horizontal"}) do |f| %>
...
  <%= f.nested_fields_for :webinar_answers do |ff| %>
    <%= ff.text_field :title, class: "form-control input-sm" %></td>
  <% end %>
...
```

**Comment by ncri** [comment]
And line 35 (/app/views/webinar_questions/_form.html.erb:35) is the nested_fields_for call `f.nested_fields_for :webinar_answers`?

**Comment by osnysantos** [comment]
Exactly

**Comment by ncri** [comment]
Do you use any other form related gems?

Try starting a console in production and run this:

    ActionView::Helpers::FormBuilder.instance_methods.include?(:nested_fields_for)

If it returns false the gem is not loaded properly in production for some reason.
Maybe the `FormBuilder` class get's overwritten after nested_form_fields has loaded.

**Comment by osnysantos** [comment]
```
$ bundle exec rails c production
Loading production environment (Rails 4.0.0)
2.1.0 :001 > ActionView::Helpers::FormBuilder.instance_methods.include?(:nested_fields_for)
 => true
```

Seems something missed but I've checked and found nothing.

**Comment by ncri** [comment]
Hm, so strange. Running out of ideas currently... ;-) Never seen this behavior before. You could try to make a very simple rails 4/ruby 2.1 test app with a very simple nested_form and see if that works. That way you can exclude influences from other gems and your app code.

**Comment by osnysantos** [comment]
Yeah, for sure. I'll try. So strange!

**Comment by osnysantos** [comment]
While Im trying to send a version for you I guess it worth mention I'm using no form related gem and my app is deployed in a VM with two apps, both is using nested_form_fields but I'm not sure if could be some conflict.

**Comment by ncri** [comment]
Closing this as it doesn't seem to be related to nested_form_fields. Feel free to reopen if you have an example app to reproduce the issue.
